services:
  - type: web
    name: WesternPumps
    rootDir: backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: "postgresql://marcos_noel23:xwszqrbJEzg3EMfZ3jp3xiknFzJ5Pidi@dpg-d6spqstm5p6s73b01030-a.oregon-postgres.render.com/westernpumps?sslmode=require"
      - key: JWT_SECRET
        value: "westernpumps-jwt-secret-key-2024-secure"
      - key: CORS_ORIGINS
        value: "https://western-pumps-np2i.vercel.app,https://westernpumps-vk0u.onrender.com"
      - key: DISABLE_AUTH
        value: "false"
      - key: ENABLE_AUTH_BOOTSTRAP
        value: "true"
      - key: SEED_ADMIN_EMAIL
        value: "admin@gmail.com"
      - key: SEED_ADMIN_PASSWORD
        value: "Westernpumps@26"
      - key: SEED_ADMIN_FULL_NAME
        value: "Admin"
      - key: ENFORCE_HTTPS
        value: "true"
